name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

      # testing front-end
      - run: docker build -t react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true react-test npm run test

      # build prod images + push to docker hub
      - run: docker build -t trungtranlebao285/multi-client ./client
      - run: docker build -t trungtranlebao285/multi-server ./server
      - run: docker build -t trungtranlebao285/multi-nginx ./nginx
      - run: docker build -t trungtranlebao285/multi-worker ./worker

      - run: docker push trungtranlebao285/multi-client
      - run: docker push trungtranlebao285/multi-server
      - run: docker push trungtranlebao285/multi-nginx
      - run: docker push trungtranlebao285/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Multi-docker-AL2023
          environment_name: Multi-docker-AL2023-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-396913704976
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip